from gtts import gTTS          # Google Text-to-Speech (online TTS)
import os                     # File and directory operations
import uuid                   # For generating unique filenames
import pygame                 # For reliable audio playback (Windows-safe)
import time                   # For small delays (file lock handling)


# ==============================
# AUDIO CONFIGURATION
# ==============================

# Directory to temporarily store generated TTS audio files
# These files are deleted immediately after playback
AUDIO_DIR = "tts_audio"

# Create the directory if it does not exist
# Prevents runtime errors when saving audio files
os.makedirs(AUDIO_DIR, exist_ok=True)

# Initialize pygame's audio mixer once at startup
# This prepares the system for audio playback
pygame.mixer.init()


# ==============================
# TEXT-TO-SPEECH FUNCTION
# ==============================

def speak(text):
    """
    Converts text into speech using Google Text-to-Speech
    and plays it aloud to the user.

    Parameters:
        text (str): The text response generated by the assistant
    """

    # If the text is empty or contains only whitespace,
    # do not attempt to generate or play audio
    if not text.strip():
        return

    # Generate a unique filename for the temporary audio file
    # UUID prevents filename collisions
    filename = os.path.join(AUDIO_DIR, f"{uuid.uuid4()}.mp3")

    # ------------------------------
    # 1. GENERATE SPEECH (gTTS)
    # ------------------------------
    tts = gTTS(text=text, lang="en")
    tts.save(filename)

    # ------------------------------
    # 2. PLAY AUDIO (pygame)
    # ------------------------------
    pygame.mixer.music.load(filename)
    pygame.mixer.music.play()

    # Wait until audio playback finishes
    # This prevents the file from being deleted too early
    while pygame.mixer.music.get_busy():
        pygame.time.Clock().tick(10)

    # ------------------------------
    # 3. CLEANUP (IMPORTANT FOR WINDOWS)
    # ------------------------------
    # Stop playback and release file handle
    pygame.mixer.music.stop()
    pygame.mixer.music.unload()

    # Short delay ensures Windows fully releases the file
    time.sleep(0.1)

    # Safely delete the temporary audio file
    os.remove(filename)


# ==============================
# SPEECH-TO-TEXT FUNCTION
# ==============================

def listen():
    """
    Listens to the user's voice input through the microphone
    and converts it into text using Google's speech recognition.

    Returns:
        str: Recognized speech text
        str: Empty string if recognition fails
    """

    import speech_recognition as sr

    # Create a recognizer instance
    r = sr.Recognizer()

    # Use the default system microphone as input source
    with sr.Microphone() as source:
        print("Listening...")
        audio = r.listen(source)

    try:
        # Convert spoken audio to text using Google Speech Recognition
        return r.recognize_google(audio)
    except Exception:
        # If speech recognition fails (noise, silence, network),
        # return an empty string instead of crashing
        return ""
